#!/bin/bash -l

#$ -P bf528
#$ -cwd
#$ -j y
#$ -pe mpi_16_tasks_per_node 16

echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Running in directory: $PWD"

#load module
module load cufflinks

#command to run Cufflinks
#which counts how reads map to genomic regions defined by an annotation (quantify gene expression)

cufflinks --compatible-hits-norm -G /project/bf528/project_2/reference/annot/mm9.gtf -b /project/bf528/project_2/reference/mm9.fa -u -o P0_1_cufflinks -p 16 /projectnb/bf528/users/frizzled/project_5_jpatel2/Programmer/P0_1_tophat/accepted_hits.bam

echo "Job finished: $(date +%F)"
